"""Provenance models — Merkle proofs, Hedera anchors, and PoSg certificates."""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class MerkleProof(BaseModel):
    """Inclusion proof for a single cell within a Merkle tree.

    Generated by ``merkle_proof()`` in swarmrouter/data/factory/merkle.py.
    Verified by ``verify_proof(leaf_hash, proof, root)``.
    """

    leaf_hash: str = Field(..., description="SHA-256 fingerprint of the cell")
    proof: list[dict[str, str]] = Field(
        ..., description='[{"hash": "...", "side": "left"|"right"}, ...]'
    )
    root: str = Field(..., description="Merkle root of the batch")


class HederaAnchor(BaseModel):
    """On-chain anchor record from Hedera Consensus Service (HCS).

    Created by ``HederaBridge.publish_merkle_root()`` in
    swarmrouter/data/factory/hedera_bridge.py.
    Cost: ~$0.0008 per HCS message.
    """

    tx_id: str = Field(..., description="Hedera transaction ID")
    topic_id: str = Field(..., description="HCS topic ID")
    sequence: int = Field(default=0, description="Message sequence number")
    network: str = Field(default="mainnet", description="mainnet | testnet")
    verify_url: str = Field(..., description="HashScan verification URL")
    anchored_at: datetime = Field(default_factory=datetime.utcnow)
    message_type: str = Field(
        default="pair_batch",
        description="pair_batch | signal | posg_cell",
    )


class QualityGuarantee(BaseModel):
    """Quality manifest for a sealed batch.

    Maps to ``build_guarantee()`` output in swarmrouter/data/factory/guarantee.py.
    Published alongside batch data as proof of quality and provenance.
    """

    version: str = "1.0"
    product: str = "SwarmCurator Pro"
    issued_at: datetime = Field(default_factory=datetime.utcnow)
    domain: str = ""
    total_pairs: int = 0
    merkle_root: str = ""
    file_sha256: str = ""
    gate_pass_rate: float = Field(ge=0.0, le=1.0, default=0.0)
    hedera_anchor: Optional[HederaAnchor] = None
    publisher: str = "Swarm & Bee"
    hedera_id: str = "swarmandbee.hbar"


class PoSgCellAnchor(BaseModel):
    """Proof-of-Signal cell-level Hedera anchoring.

    Only royal_jelly tier cells (score >= 95) receive individual on-chain
    provenance. Honey/pollen/propolis are covered by batch-level Merkle roots.
    This keeps cost proportional to quality.

    The PoSg certificate is published as a compact HCS message (<1024 bytes):

        {"type": "posg_cell", "cell_id": "HIVE-CRE-...", "jelly_score": 97.3,
         "tier": "royal_jelly", "fingerprint": "sha256[:32]",
         "batch_root": "merkle[:32]", "proof_index": 42,
         "ts": "ISO", "v": "1.0"}
    """

    cell_id: str
    cell_fingerprint: str = Field(..., description="SHA-256 of cell content")
    jelly_score: float = Field(ge=95.0, le=100.0)
    tier: str = Field(default="royal_jelly")
    batch_merkle_root: str = ""
    batch_merkle_proof: Optional[MerkleProof] = None
    hedera_anchor: Optional[HederaAnchor] = None
    anchored_by: str = "swarmandbee.hbar"
